export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS'
export const CREATE_LIST_ERROR = 'CREATE_LIST_ERROR'

export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS'
export const UPDATE_LIST_ERROR = 'UPDATE_LIST_ERROR'

export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS'
export const DELETE_LIST_ERROR = 'DELETE_LIST_ERROR'

export const LOAD_LISTS_SUCCESS = 'LOAD_LISTS_SUCCESS'
export const UNLOAD_LISTS_SUCCESS = 'UNLOAD_LISTS_SUCCESS'
