export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR'

export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR'

export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR'

export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS'
export const UNLOAD_ITEMS_SUCCESS = 'UNLOAD_ITEMS_SUCCESS'
